WITH ORDERED_RESERVATIONS AS (
    SELECT ID, USER_ID, START_TIME, END_TIME
    FROM RESERVATION
),
CHECKED_RESERVATIONS AS (
    SELECT curr.ID, curr.USER_ID, curr.START_TIME, curr.END_TIME,
            LAG(curr.START_TIME) OVER (ORDER BY curr.ID) AS PrevStartTime,
            LAG(curr.END_TIME) OVER (ORDER BY curr.ID) AS PrevEndTime
    FROM ORDERED_RESERVATIONS AS curr
)

SELECT ID, START_TIME, END_TIME
FROM CHECKED_RESERVATIONS
WHERE PrevEndTime IS NULL or (PrevEndTime <= START_TIME and PrevEndTime <= END_TIME) or (PrevStartTime >= END_TIME and PrevStartTime >= START_TIME)
ORDER BY START_TIME
