SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT AS p
JOIN APPOINTMENT AS a
ON p.PT_NO = a.PT_NO
JOIN DOCTOR AS d
ON a.MDDR_ID = d.DR_ID
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;
