SELECT b.WRITER_ID, u.NICKNAME, CONCAT(u.CITY,' ',u.STREET_ADDRESS1,' ',u.STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD as b
JOIN USED_GOODS_USER as u
ON b.WRITER_ID = u.USER_ID
WHERE b.WRITER_ID IN (SELECT WRITER_ID
                        FROM USED_GOODS_BOARD
                        GROUP BY WRITER_ID
                        HAVING COUNT(*) >= 3)
GROUP BY b.WRITER_ID
ORDER BY b.WRITER_ID DESC;
