-- https://school.programmers.co.kr/learn/courses/30/lessons/151141

SELECT 
    RH.HISTORY_ID,
    ROUND(
        C.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1)* (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100),
        0
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN 
    CAR_RENTAL_COMPANY_CAR C ON RH.CAR_ID = C.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
    ON C.CAR_TYPE = D.CAR_TYPE 
    AND (
        (D.DURATION_TYPE = '7일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) >= 7 AND DATEDIFF(RH.END_DATE, RH.START_DATE) < 30)
        OR (D.DURATION_TYPE = '30일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) >= 30 AND DATEDIFF(RH.END_DATE, RH.START_DATE) < 90)
        OR (D.DURATION_TYPE = '90일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) >= 90)
    )
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    RH.HISTORY_ID DESC;