
-- SELECT i.ITEM_ID, ITEM_NAME, RARITY
-- FROM ITEM_INFO i JOIN ITEM_TREE t ON i.ITEM_ID=t.ITEM_ID
-- WHERE i.ITEM_ID NOT IN (
--     SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
-- ORDER BY i.ITEM_ID DESC

-- 생각해보니까 JOIN을 할 필요가 없었음

SELECT i.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO i JOIN ITEM_TREE t ON i.ITEM_ID=t.ITEM_ID
WHERE i.ITEM_ID NOT IN (
    SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY i.ITEM_ID DESC
