-- 자동차 평균 대여 기간 구하기(programmers)
-- DATEDIFF(END_DATE, START_DATE)에 +1을 안해줘서 틀림
-- 시작일과 종료일을 포함하지 않는 차이를 계산하기 때문

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
