-- [PROGRAMMERS] SELECT > 부모의 형질을 모두 가지는 대장균 찾기

SELECT s.ID, s.GENOTYPE, p.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA s, ECOLI_DATA p
WHERE s.PARENT_ID = p.ID
  AND s.GENOTYPE & p.GENOTYPE = p.GENOTYPE
ORDER BY 1;
