(SELECT CONCAT(CITY,  ' ', LENGTH(CITY))
FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY
LIMIT 1)

UNION ALL 

(SELECT CONCAT(CITY,  ' ', LENGTH(CITY))
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1);
