-- 코드를 작성해주세요
WITH SCORE_TABLE AS(
    SELECT EMP_NO, SUM(SCORE) AS SCORE 
    FROM HR_GRADE
    GROUP BY EMP_NO)
    
SELECT SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES A JOIN SCORE_TABLE B ON A.EMP_NO = B.EMP_NO
WHERE SCORE IN (SELECT MAX(SCORE) FROM SCORE_TABLE)
