-- 코드를 작성해주세요
WITH FISH_INFO_LE AS(
    SELECT ID, FISH_TYPE,
        CASE WHEN LENGTH IS NULL THEN 10
            WHEN LENGTH IS NOT NULL THEN LENGTH
            END AS LENGTH
    FROM FISH_INFO)
            
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE FROM FISH_INFO_LE
GROUP BY FISH_TYPE HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
