-- 코드를 작성해주세요
WITH MX AS ( 
SELECT ID, YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, 
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE
FROM ECOLI_DATA)
 

SELECT YEAR, MAX_SIZE-SIZE_OF_COLONY AS YEAR_DEV, ID
FROM MX
ORDER BY YEAR, YEAR_DEV;
