-- 코드를 작성해주세요
WITH AVG_LENGTH AS (
    SELECT CASE WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
            END AS LENGTH
    FROM FISH_INFO)
SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH FROM AVG_LENGTH

