-- https://www.hackerrank.com/challenges/weather-observation-station-20/problem?isFullScreen=true

-- SELECT LAT_N, ROW_NUM, TOTAL_COUNT
-- FROM
--     (SELECT  LAT_N
--             , ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROW_NUM
--             , (SELECT COUNT(*)FROM STATION) AS TOTAL_COUNT
--     FROM STATION) AS TMP

-- WHERE (CAST(TOTAL_COUNT AS SIGNED) - 2*ROW_NUM) BETWEEN 0 AND 2

WITH TMP AS (
    SELECT LAT_N
        , ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROW_NUM
        , (SELECT COUNT(*) FROM STATION) AS TOTAL_COUNT
    FROM STATION
)
SELECT ROUND(LAT_N, 4)
FROM TMP
WHERE 2 * ROW_NUM >= TOTAL_COUNT
AND (2 * ROW_NUM - TOTAL_COUNT) BETWEEN 0 AND 2;

-- SELECT  LAT_N
--     , ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROW_NUM
--     , (SELECT COUNT(*)FROM STATION) AS TOTAL_COUNT
-- FROM STATION





