-- (https://school.programmers.co.kr/learn/courses/30/lessons/59412, Lv.2)

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >=9 AND HOUR(DATETIME)<20
GROUP BY 1
ORDER BY 1;
