-- (https://school.programmers.co.kr/learn/courses/30/lessons/131532, Lv.4)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, ui.GENDER, COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO AS ui
JOIN ONLINE_SALE AS os
ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;
