-- https://school.programmers.co.kr/learn/courses/30/lessons/293261
-- Kinda hard...I used two selects but maybe rownumber would work better?

SELECT 
    FI.ID AS ID,
    FNI.FISH_NAME AS FISH_NAME,
    FI.LENGTH AS LENGTH
FROM FISH_INFO FI
INNER JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
INNER JOIN (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS FISH_LENGTH ON FI.FISH_TYPE = FISH_LENGTH.FISH_TYPE
WHERE FI.LENGTH = FISH_LENGTH.MAX_LENGTH
ORDER BY FI.ID ASC;


-- ROW NUMBER Solution
-- SELECT 
--     FI.ID AS ID,
--     FNI.FISH_NAME AS FISH_NAME,
--     FI.LENGTH AS LENGTH
-- FROM (
--     SELECT 
--         FI.ID,
--         FI.FISH_TYPE,
--         FI.LENGTH,
--         ROW_NUMBER() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS rn
--     FROM FISH_INFO FI
-- ) FI
-- INNER JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
-- WHERE FI.rn = 1
-- ORDER BY FI.ID ASC;