-- 코드를 입력하세요
'개쉬운 풀이'
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY O.DATETIME - I.DATETIME DESC
LIMIT 2;


'DATEDIFF() 풀이'
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(b.DATETIME,a.datetime) DESC 
LIMIT 2;

'굳이굳이 JOIN USING이랑 섭쿼리'
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
INNER JOIN (
   SELECT ANIMAL_ID, DATETIME AS D
   FROM ANIMAL_OUTS
) A
USING (ANIMAL_ID)
ORDER BY DATETIME - D
LIMIT 2;
