-- [PROGRAMMERS] GROUP BY > 저자 별 카테고리 별 매출액 집계하기

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) TOTAL_SALES
FROM BOOK_SALES s LEFT JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
     INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(s.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY b.CATEGORY, a. AUTHOR_NAME, a.AUTHOR_ID
ORDER BY 1, 3 DESC;
