-- [PROGRAMMERS] SELECT > 대장균의 크기에 따라 분류하기 2

SELECT ID, CASE WHEN A.RANKING * 100 / TOTAL <= 25 THEN 'CRITICAL'
                WHEN A.RANKING * 100 / TOTAL <= 50 THEN 'HIGH'
                WHEN A.RANKING * 100 / TOTAL <= 75 THEN 'MEDIUM'
                ELSE 'LOW'
           END COLONY_NAME
FROM (SELECT *,
             RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) RANKING,
             COUNT(*) OVER () AS TOTAL
      FROM ECOLI_DATA) A
ORDER BY 1
