SELECT DISTINCT A.HACKER_ID, A.NAME
FROM HACKERS A
    JOIN SUBMISSIONS B ON A.HACKER_ID = B.HACKER_ID
    JOIN CHALLENGES C ON B.CHALLENGE_ID = C.CHALLENGE_ID
    JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE D.SCORE = B.SCORE
GROUP BY A.NAME, A.HACKER_ID HAVING COUNT(NAME) > 1
ORDER BY COUNT(NAME) DESC, A.HACKER_ID
