-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

WITH USER_STATS AS (
    SELECT 
        COUNT(USER_ID) AS TOTAL_USERS
    FROM 
        USER_INFO
    WHERE 
        JOINED BETWEEN '2020-12-31' AND '2022-01-01'
),
PURCHASE_STATS AS (
    SELECT 
        YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH, 
        COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS
    FROM 
        ONLINE_SALE OS
    INNER JOIN 
        USER_INFO UI ON OS.USER_ID = UI.USER_ID
    WHERE 
        UI.JOINED BETWEEN '2020-12-31' AND '2022-01-01'
    GROUP BY 
        YEAR(SALES_DATE), MONTH(SALES_DATE)
)
SELECT 
    PS.YEAR,
    PS.MONTH,
    PS.PURCHASED_USERS,
    ROUND(PS.PURCHASED_USERS * 1.0 / US.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM 
    PURCHASE_STATS PS
CROSS JOIN 
    USER_STATS US
ORDER BY 
    PS.YEAR ASC, PS.MONTH ASC;
