-- https://school.programmers.co.kr/learn/courses/30/lessons/131116
-- 또 다시 이중 SELECT문...더 좋은 방법이 있을까?

SELECT 
    FP.CATEGORY, 
    FP.PRICE AS MAX_PRICE, 
    FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MAX_PRICES ON FP.CATEGORY = MAX_PRICES.CATEGORY AND FP.PRICE = MAX_PRICES.MAX_PRICE
ORDER BY FP.PRICE DESC;