-- 대장균들의 자식 구하기(programmers)
-- 해당 문제에서는 비교 표현식이 2개 뿐이라 IFNULL와 COALESCE, 둘 중 어느 것을 사용해도 ㄱㅊ

-- IFNULL 사용
SELECT ID,
NULLIF((SELECT COUNT(*) FROM ECOLI_DATA WHERE PARENT_ID = A.ID), 0) AS CHILD_COUNT
FROM
    ECOLI_DATA A
ORDER BY
    ID;

-- COALESCE 사용
SELECT ID,
COALESCE((SELECT COUNT(*) FROM ECOLI_DATA WHERE PARENT_ID = A.ID), 0) AS CHILD_COUNT
FROM
    ECOLI_DATA A
ORDER BY
    ID;
