SELECT
    o.SALES_DATE,
    o.PRODUCT_ID,
    o.USER_ID,
    o.SALES_AMOUNT
FROM ONLINE_SALE AS o
WHERE o.SALES_DATE >= DATE '2022-03-01'
  AND o.SALES_DATE <  DATE '2022-04-01'

UNION ALL

SELECT
    f.SALES_DATE,
    f.PRODUCT_ID,
    CAST(NULL AS INTEGER) AS USER_ID,  -- 오프라인은 USER_ID 없음
    f.SALES_AMOUNT
FROM OFFLINE_SALE AS f
WHERE f.SALES_DATE >= DATE '2022-03-01'
  AND f.SALES_DATE <  DATE '2022-04-01'

ORDER BY
    SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC;
