SELECT
    DATE_FORMAT(o.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, # Fix: DATE_FORMAT()으로 날짜 형식 통합 
    o.PRODUCT_ID,
    o.USER_ID,
    o.SALES_AMOUNT
FROM ONLINE_SALE AS o
WHERE 1=1 # Fix: WHERE 1=1 명시 => WHERE 조건을 동적으로 붙일 때 편리 
  AND o.SALES_DATE >= DATE '2022-03-01'
  AND o.SALES_DATE <  DATE '2022-04-01'

UNION ALL 

SELECT
    DATE_FORMAT(f.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, # Fix: DATE_FORMAT()
    f.PRODUCT_ID,
    CAST(NULL AS INTEGER) AS USER_ID,  -- 오프라인은 USER_ID 없음
    f.SALES_AMOUNT
FROM OFFLINE_SALE AS f
WHERE 1=1 # Fix: WHERE 1=1 
  AND f.SALES_DATE >= DATE '2022-03-01'
  AND f.SALES_DATE <  DATE '2022-04-01'

ORDER BY
    SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC;
