SELECT
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    O.NAME
FROM
    ANIMAL_INS  AS I
JOIN
    ANIMAL_OUTS AS O
    ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE
    I.SEX_UPON_INTAKE    LIKE 'Intact%'
    AND (
        O.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR O.SEX_UPON_OUTCOME LIKE 'Neutered%'
    )
ORDER BY
    I.ANIMAL_ID;
