SELECT DISTINCT(CITY)
FROM STATION
WHERE CITY LIKE 'a%' 
    OR CITY LIKE 'e%'
    OR CITY LIKE 'i%'
    OR CITY LIKE 'o%'
    OR CITY LIKE 'u%'


-- 더 효율적인 코드 (정규표현식)
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[aeiou]'
