SELECT DISTINCT O.USER_ID AS USER_ID, O.PRODUCT_ID AS PRODUCT_ID
FROM ONLINE_SALE O
WHERE
    (
        SELECT COUNT(*)
        FROM ONLINE_SALE OS
        WHERE O.USER_ID = OS.USER_ID AND O.PRODUCT_ID = OS.PRODUCT_ID
    ) > 1
ORDER BY USER_ID, PRODUCT_ID DESC
