-- 5월 식품들의 총매출 조회하기 (윤다빈)
SELECT
    FP.PRODUCT_ID      AS PRODUCT_ID,
    FP.PRODUCT_NAME    AS PRODUCT_NAME,
    SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER   AS FO
JOIN FOOD_PRODUCT AS FP
    ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE 1 = 1
  AND FO.PRODUCE_DATE >= DATE '2022-05-01'
  AND FO.PRODUCE_DATE <  DATE '2022-06-01'
GROUP BY
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    FP.PRODUCT_ID ASC;
