-- https://school.programmers.co.kr/learn/courses/30/lessons/298518

SELECT COUNT(CASE WHEN FNI.FISH_NAME IN ('BASS', 'SNAPPER') THEN 1 END) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE;


-- SELECT COUNT(*) AS FISH_COUNT
-- FROM FISH_INFO FI
-- JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
-- WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');