-- Programmers > SELECT > 조건에 부합하는 중고거래 댓글 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/164673

SELECT 
    B.TITLE AS BOARD_TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID AS REPLY_WRITER_ID,
    R.CONTENTS AS REPLY_CONTENTS,
    R.CREATED_DATE AS REPLY_CREATED_DATE
FROM 
    USED_GOODS_BOARD B
JOIN 
    USED_GOODS_REPLY R
ON 
    B.BOARD_ID = R.BOARD_ID
WHERE 
    B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY 
    R.CREATED_DATE ASC,
    B.TITLE ASC;
    B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY 
    R.CREATED_DATE ASC,
    B.TITLE ASC;

