-- [PROGRAMMERS] SUM, MIN, MAX > 연도별 대장균 크기의 편차 구하기 

SELECT YEAR(e.DIFFERENTIATION_DATE) YEAR,
       m.MAX-e.SIZE_OF_COLONY YEAR_DEV,
       e.ID
FROM ECOLI_DATA e, (SELECT MAX(SIZE_OF_COLONY) MAX, YEAR(DIFFERENTIATION_DATE) YEAR
                    FROM ECOLI_DATA
                    GROUP BY 2) m
WHERE YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY 1, 2;
