-- # SELECT a.ID, a.PARENT_ID, b.ID, IF(b.ID=a.PARENT_ID, 1, NULL)
-- # FROM ECOLI_DATA a, ECOLI_DATA b
-- # ORDER BY a.ID, a.PARENT_ID, b.ID

-- # 위 쿼리 돌려 보면서 이해했다.

SELECT b.ID, COUNT(IF(b.ID=a.PARENT_ID, 1, NULL)) AS CHILD_COUNT
FROM ECOLI_DATA a, ECOLI_DATA b
GROUP BY b.ID
ORDER BY b.ID
