-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
-- 다중 SELECT문으로 쪼개기...PARTITION BY를 쓰면 더 깔끔할 것 같다.

WITH COUNTS AS (
    SELECT
        MEMBER_ID,
        COUNT(*) AS CNT
    FROM REST_REVIEW
    WHERE MEMBER_ID IS NOT NULL
    GROUP BY MEMBER_ID
),
MAXREV AS (
    SELECT
        MEMBER_ID
    FROM COUNTS
    WHERE CNT = (SELECT MAX(CNT) FROM COUNTS)
)

SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW RR
INNER JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE
    RR.MEMBER_ID IN (SELECT MEMBER_ID FROM MAXREV)
ORDER BY
    RR.REVIEW_DATE ASC,
    RR.REVIEW_TEXT ASC;