-- https://school.programmers.co.kr/learn/courses/30/lessons/273711
-- 더 빠르게는 안 될까?

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
JOIN ITEM_INFO PARENT ON IT.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;