# LIKE '' / LIKE '%'

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
INNER JOIN ICECREAM_INFO 
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000
    AND ICECREAM_INFO.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;
