WITH T1 AS (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PERCENT
    FROM ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN SIZE_PERCENT BETWEEN 0 AND 0.25 THEN 'CRITICAL'
        WHEN SIZE_PERCENT > 0.25 AND SIZE_PERCENT <= 0.50 THEN 'HIGH'
        WHEN SIZE_PERCENT > 0.50 AND SIZE_PERCENT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM T1
ORDER BY ID
