SELECT
    ri.REST_ID,
    ri.REST_NAME,
    ri.FOOD_TYPE,
    ri.FAVORITES,
    ri.ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE), 2) AS AVG_REVIEW_SCORE
FROM REST_INFO   ri
JOIN REST_REVIEW rr
  ON rr.REST_ID = ri.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY
    ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS
ORDER BY
    AVG_REVIEW_SCORE DESC,
    ri.FAVORITES     DESC;
