-- [PROGRAMMERS] String, Date > 오랜 기간 보호한 동물(2)

-- 집계함수 사용
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID
ORDER BY o.DATETIME - i.DATETIME DESC
LIMIT 2;

-- DATEDIFF 사용
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID
ORDER BY DATEDIFF(o.DATETIME, i.DATETIME) DESC
LIMIT 2;
