-- [PROGRAMMERS] SUM, MIN, MAX > 중복 제거하기

-- 기존 답
SELECT COUNT(DISTINCT NAME) COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- DISTINCT는 NULL을 애초에 거름
SELECT COUNT(DISTINCT NAME) COUNT
FROM ANIMAL_INS;
