SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE '%Intact%', 'X', 'O') AS 중성화
FROM ANIMAL_INS
-- # WHERE SEX_UPON_INTAKE LIKE '%Neutered%'
-- #     OR SEX_UPON_INTAKE LIKE'%Spayed%'
ORDER BY ANIMAL_ID, NAME, SEX_UPON_INTAKE
