-- [PROGRAMMERS] GROUP BY > 특정 조건을 만족하는 물고기별 수와 최대 길이 구하기

-- IFNULL 활용
-- 60점 짜리 정답
SELECT COUNT(ID) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 30
ORDER BY FISH_TYPE;

-- CASE 활용
-- 100점 짜리 정답
SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT 
             CASE WHEN LENGTH IS NULL THEN 10
                  ELSE LENGTH
                  END AS LENGTH, ID, FISH_TYPE
        FROM FISH_INFO) FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;

-- 둘 다 정답인데, 점수가 왜 다른지 모르겠다 ;;
