-- 10cm 이하의 물고기들은 10cm 로 취급
-- (SELECT IF(LENGTH IS NULL, 10, LENGTH) AS LENGTH
-- FROM FISH_INFO) 서브쿼리 => FROM

SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM (SELECT IF(LENGTH IS NULL, 10, LENGTH) AS LENGTH FROM FISH_INFO) A
