-- "완료된" 중고 거래의 총금액이 70만 원 이상인 사람
-- USED_GOODS_USER 테이블에서 필요한 칼럼은 닉네임뿐,
-- USED_GOODS_BOARD 테이블에서 위 조건을 모두 충족시키는 서브쿼리 추출 -> USED_GOODS_USER테이블과 조인

SELECT b.WRITER_ID AS USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER u JOIN (
  SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD
  WHERE STATUS = "DONE"
  GROUP BY WRITER_ID
  HAVING SUM(PRICE) >= 700000) b ON u.USER_ID = b.WRITER_ID
ORDER BY TOTAL_SALES
