-- 상품 별 오프라인 매출 구하기(Programmers - JOIN)
-- 매출액 계산으로 묶어서 SELECT해주고, GROUP BY로 구분만 해주면 됨

SELECT 	p.PRODUCT_CODE, SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM PRODUCT p JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID

GROUP BY p.PRODUCT_ID

ORDER BY SALES DESC, p.PRODUCT_CODE ASC
